import React from 'react';
import { AnalysisResponse } from '../types';

interface PrintableReportProps {
  data: AnalysisResponse;
  originalIdea: string;
}

const PrintableReport: React.FC<PrintableReportProps> = ({ data, originalIdea }) => {
  const { analysis, pitchDeck } = data;
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const year = new Date().getFullYear();

  return (
    <div id="printable-section" className="hidden print:block font-serif text-black p-8 max-w-[210mm] mx-auto bg-white">
      {/* TITLE PAGE */}
      <div className="min-h-screen flex flex-col justify-center items-center text-center page-break-after-always">
        <div className="mb-8">
           <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="mx-auto text-indigo-600 mb-4">
             <path d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09z"/>
             <path d="m12 15-3-3a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.35 22.35 0 0 1-4 5l-3-3"/>
             <path d="M9 12H4s.55-3.03 2-4c1.62-1.08 5 0 5 0"/>
             <path d="M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5"/>
           </svg>
           <h1 className="text-4xl font-bold mb-4">Startup Validation Report</h1>
        </div>
        
        <div className="border-t-2 border-b-2 border-gray-100 py-8 w-full max-w-lg mx-auto mb-12">
          <h2 className="text-2xl font-medium text-gray-800 italic">"{originalIdea}"</h2>
        </div>

        <div className="mb-16">
          <p className="text-xs text-gray-400 uppercase tracking-widest mb-2">Generated By</p>
          <p className="text-xl font-bold text-indigo-800">PitchPal</p>
          <p className="text-sm text-gray-500">AI Validator & Pitch Deck Generator</p>
        </div>
        
        <p className="text-gray-500 font-medium">{date}</p>
      </div>

      <div className="page-break"></div>

      {/* SECTION 1: Viability Score */}
      <div className="mb-10 avoid-break mt-8">
        <h3 className="text-xl font-bold border-b-2 border-gray-800 mb-4 pb-2 uppercase tracking-wide">1. Viability Score</h3>
        <div className="flex items-center space-x-6">
           <div className="text-5xl font-bold text-indigo-600">{analysis.score}<span className="text-2xl text-gray-400 font-normal">/100</span></div>
           <div className="h-12 w-px bg-gray-300"></div>
           <div>
             <p className="text-sm text-gray-500 uppercase">Status</p>
             <p className="text-xl font-semibold">
               {analysis.score > 75 ? 'High Potential 🚀' : analysis.score > 50 ? 'Needs Refinement 🛠️' : 'High Risk ⚠️'}
             </p>
           </div>
        </div>
      </div>

      {/* SECTION 2: Feasibility & Fit */}
      <div className="mb-10 avoid-break">
        <h3 className="text-xl font-bold border-b-2 border-gray-800 mb-6 pb-2 uppercase tracking-wide">2. Feasibility & Fit</h3>
        
        <div className="mb-6">
          <h4 className="font-bold text-gray-800 mb-2 uppercase text-sm">Feasibility</h4>
          <p className="text-justify leading-relaxed text-gray-700">{analysis.feasibility}</p>
        </div>
        
        <div>
          <h4 className="font-bold text-gray-800 mb-2 uppercase text-sm">Problem-Solution Fit</h4>
          <p className="text-justify leading-relaxed text-gray-700">{analysis.problemSolution}</p>
        </div>
      </div>

      {/* SECTION 3: Suggestions */}
      {analysis.suggestions && analysis.suggestions.length > 0 && (
        <div className="mb-10 avoid-break">
          <h3 className="text-xl font-bold border-b-2 border-gray-800 mb-4 pb-2 uppercase tracking-wide">3. Suggestions for Improvement</h3>
          <ol className="list-decimal pl-5 space-y-3">
            {analysis.suggestions.map((s, i) => (
              <li key={i} className="text-justify leading-relaxed text-gray-700 pl-2">{s}</li>
            ))}
          </ol>
        </div>
      )}

      {/* SECTION 4: Investment */}
      <div className="mb-10 avoid-break">
        <h3 className="text-xl font-bold border-b-2 border-gray-800 mb-4 pb-2 uppercase tracking-wide">4. Investment Required</h3>
        <div className="bg-gray-50 p-6 rounded-lg border border-gray-100">
          <p className="text-sm text-gray-500 uppercase mb-1">Estimated Initial Capital</p>
          <p className="text-2xl font-bold text-gray-900">{analysis.estimatedInvestment}</p>
          <p className="text-xs text-gray-500 mt-2 italic">Note: Estimates are based on current market rates in India and may vary by location and scale.</p>
        </div>
      </div>

      {/* SECTION 5: Cost Breakdown */}
      <div className="mb-10 avoid-break">
        <h3 className="text-xl font-bold border-b-2 border-gray-800 mb-4 pb-2 uppercase tracking-wide">5. Cost Breakdown</h3>
        <table className="w-full border-collapse border border-gray-200 text-sm">
          <thead>
            <tr className="bg-gray-100">
              <th className="border border-gray-200 p-3 text-left font-bold text-gray-700">Category</th>
              <th className="border border-gray-200 p-3 text-right font-bold text-gray-700">Estimated Cost (INR)</th>
            </tr>
          </thead>
          <tbody>
            {analysis.costBreakdown.map((item, i) => (
              <tr key={i} className={i % 2 === 0 ? 'bg-white' : 'bg-gray-50'}>
                <td className="border border-gray-200 p-3 text-gray-700">{item.category}</td>
                <td className="border border-gray-200 p-3 text-right font-mono text-gray-900">₹{item.amount.toLocaleString('en-IN')}</td>
              </tr>
            ))}
            <tr className="bg-gray-100 font-bold">
               <td className="border border-gray-200 p-3 text-right">Total (Approx)</td>
               <td className="border border-gray-200 p-3 text-right font-mono">
                 ₹{analysis.costBreakdown.reduce((acc, curr) => acc + curr.amount, 0).toLocaleString('en-IN')}
               </td>
            </tr>
          </tbody>
        </table>
      </div>

      <div className="page-break"></div>

      {/* SECTION 6: Market Analysis */}
      <div className="mb-10 mt-8">
        <h3 className="text-xl font-bold border-b-2 border-gray-800 mb-4 pb-2 uppercase tracking-wide">6. Market Analysis</h3>
        <p className="text-justify leading-relaxed text-gray-700 mb-6">{analysis.marketAnalysis}</p>
        
        {analysis.sources && analysis.sources.length > 0 && (
          <div className="bg-gray-50 p-4 rounded text-xs text-gray-600 border-l-4 border-indigo-200">
            <strong className="block mb-2 uppercase text-gray-500">References / Sources:</strong>
            <ul className="list-disc pl-5 space-y-1">
              {analysis.sources.map((s, i) => <li key={i}>{s}</li>)}
            </ul>
          </div>
        )}
      </div>

      {/* SECTION 7: Business Model */}
      <div className="mb-10 avoid-break">
        <h3 className="text-xl font-bold border-b-2 border-gray-800 mb-4 pb-2 uppercase tracking-wide">7. Business Model</h3>
        <p className="text-justify leading-relaxed text-gray-700">{analysis.businessModel}</p>
      </div>

      {/* SECTION 8: Customer Segments */}
      <div className="mb-10 avoid-break">
        <h3 className="text-xl font-bold border-b-2 border-gray-800 mb-4 pb-2 uppercase tracking-wide">8. Customer Segments</h3>
        <ul className="list-disc pl-5 grid grid-cols-2 gap-x-8 gap-y-2">
          {analysis.customerSegments.map((s, i) => <li key={i} className="text-gray-700">{s}</li>)}
        </ul>
      </div>

       {/* SECTION 9: Competitors */}
       <div className="mb-10 avoid-break">
        <h3 className="text-xl font-bold border-b-2 border-gray-800 mb-4 pb-2 uppercase tracking-wide">9. Competitors</h3>
        <ul className="list-disc pl-5 grid grid-cols-2 gap-x-8 gap-y-2">
          {analysis.competitors.map((s, i) => <li key={i} className="text-gray-700">{s}</li>)}
        </ul>
      </div>

      <div className="page-break"></div>

      {/* SECTION 10: Pitch Deck */}
      <div className="mt-8">
        <h3 className="text-xl font-bold border-b-2 border-gray-800 mb-8 pb-2 uppercase tracking-wide">10. Generated Pitch Deck</h3>
        <div className="space-y-8">
          {pitchDeck.map((slide, i) => (
            <div key={i} className="border border-gray-300 rounded-lg overflow-hidden avoid-break">
              <div className="bg-gray-100 px-6 py-3 border-b border-gray-300 flex justify-between items-center">
                 <span className="font-bold text-gray-500 text-sm uppercase">Slide {i+1}</span>
                 <span className="font-bold text-indigo-800">{slide.title}</span>
              </div>
              <div className="p-6 bg-white">
                <ul className="list-disc pl-5 space-y-2 mb-6">
                  {slide.content.map((point, idx) => (
                    <li key={idx} className="text-gray-800 leading-relaxed">{point}</li>
                  ))}
                </ul>
                <div className="bg-indigo-50 p-4 rounded text-sm text-gray-700 border-l-4 border-indigo-400">
                  <span className="font-bold block mb-1 text-indigo-900">Speaker Notes:</span> 
                  {slide.notes}
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

       {/* SECTION 11: Conclusion */}
       <div className="mt-12 avoid-break">
          <h3 className="text-xl font-bold border-b-2 border-gray-800 mb-4 pb-2 uppercase tracking-wide">11. Conclusion</h3>
          <p className="text-justify leading-relaxed text-gray-700">
            This report serves as a preliminary validation of your startup concept. With a viability score of <strong>{analysis.score}/100</strong>, 
            {analysis.score > 70 ? ' the idea shows strong market potential.' : ' the idea requires addressing key challenges highlighted in the suggestions section.'} 
            Use the generated pitch deck structure as a foundation for your investor presentations.
          </p>
       </div>

       {/* Footer */}
       <div className="mt-16 pt-8 border-t border-gray-300 text-center text-xs text-gray-400 page-break-before-always">
          <p className="mb-1">Report generated using PitchPal – AI Startup Pitch Deck & Idea Validator.</p>
          <p>© {year} PitchPal. All rights reserved.</p>
       </div>
    </div>
  );
};

export default PrintableReport;